version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing pip..."
      - pip install --upgrade pip

  pre_build:
    commands:
      - echo "Cleaning and preparing build folder..."
      - rm -rf build_root
      - mkdir -p build_root

  build:
    commands:
      - echo "Copying lambda_function.py to build root..."
      - cp lambda_function.py build_root/
      - echo "Installing dependencies (if any)..."
      - if [ -f requirements.txt ]; then pip install -r requirements.txt -t build_root/; else echo "No requirements.txt found, skipping"; fi
      - cd build_root
      - echo "Verifying build contents..."
      - ls -la
      - echo "Creating deployment package..."
      - |
        echo "def lambda_handler(event, context):" > main.py
        echo "    print('Hello from Lambda')" >> main.py
        echo "    return {'statusCode': 200, 'body': 'Success'}" >> main.py
artifacts:
  files:
    - main.py
