version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install requests

  build:
    commands:
      # Store current and previous versions
      - CURRENT_VERSION=$(aws lambda get-alias --function-name FSxAnalyser --name production --query 'FunctionVersion' --output text)
      - PREVIOUS_VERSION=$(aws lambda list-versions-by-function --function-name FSxAnalyser --query 'reverse(sort_by(Versions[?Version!=`$LATEST`], &Version))[1].Version' --output text)
      - echo "Current version $CURRENT_VERSION, Previous version $PREVIOUS_VERSION"
      
      # Health check with timeout
      - |
        endpoint="https://0c345js9lc.execute-api.us-east-1.amazonaws.com/prod"
        timeout=60  # 1 minute timeout
        start_time=$(date +%s)
        
        while true; do
          current_time=$(date +%s)
          elapsed=$((current_time - start_time))
          
          if [ $elapsed -ge $timeout ]; then
            echo "Timeout after ${timeout} seconds. Rolling back..."
            aws lambda update-alias --function-name FSxAnalyser --name production --function-version $PREVIOUS_VERSION
            exit 1
          fi
          
          http_code=$(curl -vso /dev/null -w "%{http_code}" $endpoint 2>&1)
          
          if [[ $http_code == "200" ]]; then
            echo "Endpoint healthy, returned 200 OK"
            exit 0
          else
            echo "Endpoint returned $http_code, retrying... (${elapsed}s elapsed)"
            sleep 5
          fi
        done

  post_build:
    commands:
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
          echo "Deployment verified successfully!"
        else
          echo "Deployment verification failed, rollback completed"
          exit 1
        fi
