version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install requests

  pre_build:
    commands:
      # Store the current version before testing
      - CURRENT_VERSION=$(aws lambda get-alias --function-name FSxAnalyser --name production --query 'FunctionVersion' --output text)
      - echo "Current production version is $CURRENT_VERSION"
      # Get previous version for potential rollback
      - PREVIOUS_VERSION=$(aws lambda list-versions-by-function --function-name FSxAnalyser --query 'reverse(sort_by(Versions[?Version!=`$LATEST`], &Version))[1].Version' --output text)
      - echo "Previous stable version was $PREVIOUS_VERSION"

  build:
    commands:
      # Function to check endpoint health
      - |
        check_endpoint() {
          local endpoint=$1
          local max_retries=3
          local retry_count=0
          local success=false
          
          echo "Testing endpoint: $endpoint"
          
          while [ $retry_count -lt $max_retries ]; do
            HTTP_CODE=$(curl -s -o response.txt -w "%{http_code}" $endpoint)
            
            if [ $HTTP_CODE -eq 200 ]; then
              echo "Endpoint $endpoint returned 200 OK"
              success=true
              break
            elif [[ $HTTP_CODE -eq 500 || $HTTP_CODE -eq 502 || $HTTP_CODE -eq 503 || $HTTP_CODE -eq 504 ]]; then
              echo "Endpoint $endpoint returned error: $HTTP_CODE"
              cat response.txt
              retry_count=$((retry_count + 1))
              if [ $retry_count -lt $max_retries ]; then
                echo "Retrying in 5 seconds..."
                sleep 5
              fi
            else
              echo "Unexpected status code: $HTTP_CODE"
              cat response.txt
              exit 1
            fi
          done
          
          if [ "$success" = false ]; then
            echo "Endpoint $endpoint failed after $max_retries attempts"
            return 1
          fi
          
          return 0
        }

      # Test production endpoint
      - |
        if ! check_endpoint "https://0c345js9lc.execute-api.us-east-1.amazonaws.com/prod"; then
          echo "Production endpoint health check failed. Initiating rollback..."
          
          # Rollback to previous version
          echo "Rolling back production alias to version $PREVIOUS_VERSION"
          aws lambda update-alias --function-name FSxAnalyser --name production --function-version $PREVIOUS_VERSION
          
          # Verify rollback
          ROLLBACK_VERSION=$(aws lambda get-alias --function-name FSxAnalyser --name production --query 'FunctionVersion' --output text)
          echo "Rolled back to version $ROLLBACK_VERSION"
          
          # Test endpoint after rollback
          if ! check_endpoint "https://0c345js9lc.execute-api.us-east-1.amazonaws.com/prod"; then
            echo "ERROR: Endpoint still failing after rollback!"
            exit 1
          else
            echo "Rollback successful, endpoint is healthy"
            exit 1  # Still exit with error since original deployment failed
          fi
        fi

  post_build:
    commands:
      # Final verification
      - echo "Post-deployment verification successful"
      - echo "Production alias pointing to version $(aws lambda get-alias --function-name FSxAnalyser --name production --query 'FunctionVersion' --output text)"
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
          echo "Deployment successful and verified!"
        else
          echo "Deployment verification failed!"
          exit 1
        fi

artifacts:
  files:
    - response.txt
  discard-paths: yes
