version: 0.2

phases:
  pre_build:
    commands:
      - pwd
      - ls -la
      
  build:
    commands:
      # Print the contents of the input artifact directory
      - echo "Contents of input directory:"
      - ls -la
      
      # Read the version file
      - VERSION=$(cat version.txt)
      - echo "Retrieved version: $VERSION"
      
      # Update production alias to point to the tested version
      - aws lambda update-alias --function-name FSxAnalyser --name production --function-version $VERSION
      - echo "Updated production alias to version $VERSION"

artifacts:
  files:
    - version.txt
