version: 0.2

phases:
  pre_build:
    commands:
      - echo "Listing primary source contents (buildspec location)"
      - ls -la $CODEBUILD_SRC_DIR
      - echo "Listing TestVersion artifact contents"
      - ls -la $CODEBUILD_SRC_DIR_TestVersion
      
  build:
    commands:
      # Get version from TestVersion artifact
      - VERSION=$(cat $CODEBUILD_SRC_DIR_TestVersion/version.txt)
      - echo "Promoting version $VERSION to production"
      - aws lambda update-alias --function-name FSxAnalyser --name production --function-version $VERSION
      - echo "Successfully promoted version $VERSION to production"
