version: 0.2

phases:
  build:
    commands:
      - echo "Checking for version file"
      - ls -la
      - ls -la output/ || echo "output directory not found"
      - VERSION=$(cat output/version.txt || cat version.txt)
      - echo "Promoting version $VERSION to production"
      - aws lambda update-alias --function-name FSxAnalyser --name production --function-version $VERSION
      - echo "Successfully promoted version $VERSION to production"
