version: 0.2

phases:
  build:
    commands:
      - LATEST_VERSION=$(aws lambda publish-version --function-name FSxAnalyser --description "Publishing latest version for test" --query 'Version' --output text)
      - echo "Latest version is $LATEST_VERSION"
      - aws lambda update-alias --function-name FSxAnalyser --name test --function-version $LATEST_VERSION
      - echo $LATEST_VERSION > version.txt
      - echo "Updated test alias to version $LATEST_VERSION"

artifacts:
  files:
    - version.txt
  discard-paths: yes
