version: 0.2

phases:
  build:
    commands:
      # Get the $LATEST version number
      - LATEST_VERSION=$(aws lambda publish-version --function-name FSxAnalyser --description "Publishing latest version for test" --query 'Version' --output text)
      - echo "Latest version is $LATEST_VERSION"
      
      # Update test alias to point to the new version
      - aws lambda update-alias --function-name FSxAnalyser --name test --function-version $LATEST_VERSION
      
      # Save the version number for potential production promotion
      - mkdir -p output
      - echo $LATEST_VERSION > output/version.txt
      - echo "Updated test alias to version $LATEST_VERSION"

artifacts:
  files:
    - output/version.txt
  discard-paths: no
